feat: add implementation to support safari web push
pimeys/a2 pull request #57
Opened 2021-11-04 19:28 UTC by hortopan

* Added support for safari web push.

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html

```json
{
 "aps": {
    "alert": {
        "title": "Flight A998 Now Boarding",
        "body": "Boarding has begun for Flight A998.",
        "action": "View"
    },
 "url-args": ["arg1", "arg2"]
 }
}

```

2021-11-04 19:32 UTC, pimeys commented
Cool. Is this something that also could be done with https://github.com/pimeys/rust-web-push

I will merge this if you feel it's important to have here, but I have no means to test any of the code...

2021-11-04 19:39 UTC, hortopan commented
> Cool. Is this something that also could be done with https://github.com/pimeys/rust-web-push

Safari's web push is not based on web push protocol (with web workers, etc) so it doesn't work with regular web pushes as everything needs to go through Apple's apns.  

I think this could potentially be implemented as a dependency within `pimeys/rust-web-push` so that we have support across the board.

2021-11-04 21:54 UTC, pimeys requested changes

2021-11-04 21:54 UTC, pimeys commented on src/request/notification/web.rs
> +    url_args: &'a Vec<&'a str>,
This could be `&'a [&'a str]`.

2021-11-04 21:54 UTC, pimeys commented on src/request/notification/web.rs
> +    pub fn new(alert: WebPushAlert<'a>, url_args: &'a Vec<&'a str>) -> WebNotificationBuilder<'a> {
same here

2021-11-05 07:57 UTC, pimeys approved these changes

2021-11-05 08:08 UTC, merged